### ISSUE TITLE
Question about some file path

### ISSUE THREAD

**Issue by zw-SIMM** [pgmikhael/clipzyme#2]
Nice work and beautiful codes! But some question about file path.
What is the file ```alphafold_enzymes.p``` and ```uniprot2sequence_standard_set_structs.p``` in ```clipzyme/datasets/enzyme_screening.py``` ? How to generate these files?

```python

     self.alphafold_files = pickle.load(open("/home/datasets/alphafold_enzymes.p", "rb"))

....

    @staticmethod
    def set_args(args) -> None:
        args.dataset_file_path = (
            "/home/datasets/uniprot2sequence_standard_set_structs.p"
        )
```

Additionally, ```args.load_wln_cache_in_dataset``` seems missing.

**Comment by pgmikhael** [comment]
Hi, 

Thank you for your interest!

Here, 

- `alphafold_enzymes.p` would be a set of protein (UniProt) IDs that have an alpha-fold structure saved locally (this is only used in the `skip_sample` method to save time from checking whether the path exists with something like `os.path.exists`)
- `uniprot2sequence_standard_set_structs.p`: is a dict mapping a protein ID to its sequence, similar to the `uniprot2sequence.p` file. 

Thanks for pointing out the `--load_wln_cache_in_dataset` flag. This should be False / not used. We will fix it in the next code update as well!

**Comment by zw-SIMM** [comment]
> Hi,
> 
> Thank you for your interest!
> 
> Here,
> 
> * `alphafold_enzymes.p` would be a set of protein (UniProt) IDs that have an alpha-fold structure saved locally (this is only used in the  method to save time from checking whether the path exists with something like `skip_sample``os.path.exists`)
> * `uniprot2sequence_standard_set_structs.p`: is a dict mapping a protein ID to its sequence, similar to the  file.`uniprot2sequence.p`
> 
> Thanks for pointing out the flag. This should be False / not used. We will fix it in the next code update as well!`--load_wln_cache_in_dataset`

Many thanks for your reply! The simplest method seems to comment them in ```load_dataset``` method and ```skip_sample```method ?

**Comment by zw-SIMM** [comment]
But I'm still confused about the generation of these files, would you mind providing the generation codes?

```python
            self.metadata_json = pickle.load(open(args.dataset_file_path, "rb"))
            self.alphafold_files = pickle.load(
                open("/home/datasets/alphafold_enzymes.p", "rb")
            )
            self.quickprot_caches = pickle.load(
                open("/home/datasets/quickprot_caches.p", "rb")
            )
            self.msa_files = pickle.load(
                open(
                    "/home/datasets/uniprot2msa_embedding.p",
                    "rb",
                )
            )```

**Comment by pgmikhael** [comment]
Yes I think that should work. I'll also just clean up because some code is unused in the final version.
